export enum AuthExceptionEnum {
  VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  CODE_PASSWORD_NOTFOUND = "CODE_PASSWORD_NOTFOUND",
  CODE_PASSWORD_EXPIRED = "CODE_PASSWORD_EXPIRED",
}

export enum HttpExceptionEnum {
  UNPROCESSED_ENTITY = "UNPROCESSED_ENTITY",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION",
}
